### ISSUE TITLE
Redundant prompt

### ISSUE THREAD

**Issue by henrikmdev** [LauritsCSB/QuizMaker#1]
https://github.com/LauritsCSB/QuizMaker/blob/9f7f57f20d28cc35ccdca67ca9c37217f5d64242/UIMethods.cs#L26

I noticed that in your main function, you call this method 4 times. It may be redundant for the user to keep getting the same prompt 4 times in a row.

**Comment by LauritsCSB** [comment]
I agree! This doesn't seem polished at all
