### ISSUE TITLE
This blocks of code should be separate own functions

### ISSUE THREAD

**Issue by incredibleLeitman** [LauritsCSB/QuizMaker#16]
https://github.com/LauritsCSB/QuizMaker/blob/50fb4a20dd01779764fa7169805eb6b49d5e08ec/Program.cs#L31-L34

https://github.com/LauritsCSB/QuizMaker/blob/50fb4a20dd01779764fa7169805eb6b49d5e08ec/Program.cs#L41-L44

This is a nice use case for functions that serialize given data to specific files and read back from them.

Also think about, in which modules you need the "path" and "serializer" variables and put it there to encapsulate your code.
Maybe those could also be constants or readonly variables? 😏

**Comment by LauritsCSB** [comment]
Please explain what you mean by modules? :)

**Comment by incredibleLeitman** [comment]
By Modules I mean parts thar logically split your code. In this case I refer to your ui, logic or program classes :D
