### ISSUE TITLE
Do not use magic numbers

### ISSUE THREAD

**Issue by incredibleLeitman** [LauritsCSB/QuizMaker#19]
https://github.com/LauritsCSB/QuizMaker/blob/c3c72341f5ccb020538903f00912d876e373fa6d/UIMethods.cs#L45
In this case the "3" is pretty much obvious what it stands for,
but to be able to maintain your program in the future (for example if you want to support more or less answers) you should define such values as constants somewhere

**Comment by LauritsCSB** [comment]
Thanks. In the future i'd like to expand the functionality of the app to support more or less answers!
