### ISSUE TITLE
Prefer returning values from functions instead of overriding the passed parameter

### ISSUE THREAD

**Issue by incredibleLeitman** [LauritsCSB/QuizMaker#20]
https://github.com/LauritsCSB/QuizMaker/blob/5e2629a35cd148e2efdbd95b57d1fc4d3a37d819/UIMethods.cs#L43-L51

This can be very confusing if you pass some variable to a function which returns void and some time later you notice that the values of the variable have changed.
To make this easier visible to the reader you should create a temporary variable within the function and return it 
to override the value of the variable after the call.
You did exactly this for the Question:

```
public static string SetQuestion()
{
  Console.WriteLine("Enter question: ");
  string question = Console.ReadLine();
  return question;
}

Question.Question = UIMethods.SetQuestion();
```

**Comment by LauritsCSB** [comment]
I get you point. I could solve this by copying the functionality from the setQuestion method (no loop), return single string from method and add those to answersList within a loop, would that be a better solution? Also, should that loop be in a logic method? @incredibleLeitman
