### ISSUE TITLE
CurrentQuestion should start with a lowercase letter

### ISSUE THREAD

**Issue by incredibleLeitman** [LauritsCSB/QuizMaker#27]
https://github.com/LauritsCSB/QuizMaker/blob/79ae9dd448b3aab5a31f45b60c4c2a472a19bc43/Program.cs#L39

Keep in mind this also applies to function parameters 👆 
https://github.com/LauritsCSB/QuizMaker/blob/79ae9dd448b3aab5a31f45b60c4c2a472a19bc43/LogicMethods.cs#L15

**Comment by LauritsCSB** [comment]
Will i ever learn!?
