### ISSUE TITLE
Return from function on invalid input

### ISSUE THREAD

**Issue by incredibleLeitman** [LauritsCSB/QuizMaker#28]
https://github.com/LauritsCSB/QuizMaker/blob/79ae9dd448b3aab5a31f45b60c4c2a472a19bc43/UIMethods.cs#L79-L95

Currently if the user enters an invalid answer the output is
"Try Again"
"Wrong!"

Instead you could just return from the function after detecting invalid input and don't print an additional "Wrong"

**Comment by LauritsCSB** [comment]
I agree that getting two messages is a bit too much. The idea was to print a response both for input that's out of index range and for wrong answer.
