### ISSUE TITLE
Count() is different from Count!

### ISSUE THREAD

**Issue by incredibleLeitman** [LauritsCSB/QuizMaker#29]
https://github.com/LauritsCSB/QuizMaker/blob/79ae9dd448b3aab5a31f45b60c4c2a472a19bc43/UIMethods.cs#L63

Be careful when using this ☝️ 
"Count()" with brackets is an overload for a LINQ statement that would allow you to count all elements in your list that support specific given properties,
whereas "Count" without brackets just returns the stored current amount of elements in your list.

In practice this does not matter as the result is the same,
but on older hardware the Linq version does a lot more calculations and is less performant then just accessing one field.

**Comment by LauritsCSB** [comment]
Thank you. I didn't even intend to use the brackets
