### ISSUE TITLE
Reword question prompt

### ISSUE THREAD

**Issue by henrikmdev** [LauritsCSB/QuizMaker#3]
https://github.com/LauritsCSB/QuizMaker/blob/9f7f57f20d28cc35ccdca67ca9c37217f5d64242/UIMethods.cs#L43

Very minor point, but maybe reword this because a "guess" connotes the idea that the user doesn't actually know the answer and is just guessing. But the user may actually know the answer because he/she studied hard :)

**Comment by LauritsCSB** [comment]
I like your point!
