### ISSUE TITLE
Optional: This method does not prevent or even detect if the given answers contains at least one correct answer

### ISSUE THREAD

**Issue by incredibleLeitman** [LauritsCSB/QuizMaker#30]
https://github.com/LauritsCSB/QuizMaker/blob/79ae9dd448b3aab5a31f45b60c4c2a472a19bc43/UIMethods.cs#L46-L58

Especially with the printing of your answers
```Console.WriteLine($"{answerIndex + 1}. {CurrentQuestion.Answers[answerIndex].TrimEnd('*')}");```
your program takes a very hard assumption on how those answers should be entered.

You could ensure that the given Quizcards are in valid format when entered so that the assumption of your program is usually correct.
("usually" because then there would still be the option to modify the serialized files and produce invalid cards, but I won't go into too much detail about that ^^)

**Comment by LauritsCSB** [comment]
That's something ive done myself and had to redo the whole quiz because i forgot to add the * in the end. Good point.

**Comment by LauritsCSB** [comment]
Closed this with a reference to an nonexistent issue (#31)

**Comment by incredibleLeitman** [comment]
Be carefull 👆 this solution introduced a bug:
If the user enters for example 3 answers, without a * the function detects that this is not valid and asks the user again
BUT appends the new answers to the existing ones!

To fix this you probably want to either call List.Clear() when detecting wrong input
or just create a new List within your do - while loop

**Comment by incredibleLeitman** [comment]
Also notice that you could put the code of this loop
```
foreach (var answer in answers)
{
  if (answer.Contains('*'))
  {
    correctAnswerCounter++;
  }
}
```
directly into the first for loop where the user enters the question
